#!/usr/bin/env python3
"""Post-process Playwright's own HTML report to add video speed controls
and a link to the test-case-matrix (docs/qa/<slug>/test-matrix.md), if any
exist.

Playwright's built-in `html` reporter (enabled in playwright.config.ts)
already writes docs/qa/playwright-report/index.html with everything a
report needs: status filters (All/Passed/Failed/Flaky/Skipped) with
counts, a search box, per-test steps, file:line locations, browser
project badges, and retries as tabs. This script does not reimplement any
of that — it only appends two small pieces on top:

1. A vanilla-JS snippet that finds `<video>` elements (a plain HTML5 tag,
   not part of Playwright's internal React bundle, so this stays stable
   across Playwright versions) and adds slow-motion playback controls next
   to them, since a real run is fast enough to be hard to follow at 1x.
2. A floating "Test Matrix" button linking out to an HTML render of every
   docs/qa/<slug>/test-matrix.md this project has (produced by the
   test-case-matrix skill) — so a tester can jump from a run's pass/fail
   report to the scenario list/traceability table that run was checking
   off, without leaving the browser.

Usage:
    python scripts/build_report.py
"""
import html as html_lib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QA_DIR = ROOT / "docs" / "qa"
REPORT_PATH = QA_DIR / "playwright-report" / "index.html"

MARKER = "<!-- webapp-testing:video-speed-controls -->"
MATRIX_MARKER = "<!-- webapp-testing:test-matrix-link -->"

DEFAULT_PLAYBACK_RATE = 0.5

INJECTED_SCRIPT = f"""{MARKER}
<style>
.wt-speed-controls {{
  display: flex; align-items: center; gap: .3rem; margin: .4rem 0 0;
  font: 12px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}}
.wt-speed-controls span {{ color: var(--color-fg-muted, #666); margin-right: .2rem; }}
.wt-speed-btn {{
  border: 1px solid var(--color-border-default, #d0d7de); background: var(--color-canvas-default, #fff);
  color: var(--color-fg-default, #1f2328); border-radius: 6px; padding: .15rem .45rem;
  font-size: .72rem; cursor: pointer; font-variant-numeric: tabular-nums;
}}
.wt-speed-btn:hover {{ border-color: #2563eb; }}
.wt-speed-btn.active {{ background: #2563eb; border-color: #2563eb; color: #fff; }}
</style>
<script>
(function () {{
  var DEFAULT_RATE = {DEFAULT_PLAYBACK_RATE};
  var RATES = [0.25, 0.5, 1, 1.5];

  function enhance(video) {{
    if (video.dataset.wtEnhanced) return;
    video.dataset.wtEnhanced = "1";
    video.defaultPlaybackRate = DEFAULT_RATE;
    video.playbackRate = DEFAULT_RATE;

    var bar = document.createElement("div");
    bar.className = "wt-speed-controls";
    var label = document.createElement("span");
    label.textContent = "Speed:";
    bar.appendChild(label);
    RATES.forEach(function (rate) {{
      var btn = document.createElement("button");
      btn.type = "button";
      btn.className = "wt-speed-btn" + (rate === DEFAULT_RATE ? " active" : "");
      btn.textContent = rate + "\\u00d7";
      btn.addEventListener("click", function () {{
        video.playbackRate = rate;
        bar.querySelectorAll(".wt-speed-btn").forEach(function (b) {{
          b.classList.toggle("active", b === btn);
        }});
      }});
      bar.appendChild(btn);
    }});
    if (video.parentNode) {{
      video.parentNode.insertBefore(bar, video.nextSibling);
    }}
  }}

  function sweep() {{
    document.querySelectorAll("video").forEach(enhance);
  }}

  sweep();
  new MutationObserver(sweep).observe(document.body, {{ childList: true, subtree: true }});
}})();
</script>
"""


def _render_matrix_markdown(md_text: str) -> str:
    """Minimal markdown -> HTML for test-matrix.md's known shape (headers,
    bold, inline code, links, and GFM tables with literal <br> inside
    cells). Not a general CommonMark renderer — the input is always
    generated by the test-case-matrix skill's own template, so only the
    subset that template actually uses needs to be handled."""

    def inline(text: str) -> str:
        # Escape first, then re-allow the literal <br> the matrix template
        # puts inside Test Steps/Expected Result cells on purpose.
        text = html_lib.escape(text)
        text = text.replace("&lt;br&gt;", "<br>")
        text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
        text = re.sub(r"`([^`]+?)`", r"<code>\1</code>", text)
        text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2" target="_blank" rel="noopener">\1</a>', text)
        return text

    lines = md_text.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        heading = re.match(r"^(#{1,3})\s+(.*)$", stripped)
        if heading:
            level = len(heading.group(1))
            out.append(f"<h{level}>{inline(heading.group(2))}</h{level}>")
            i += 1
            continue

        if stripped.startswith("|") and i + 1 < len(lines) and re.match(r"^\|?\s*:?-{2,}", lines[i + 1].strip()):
            header_cells = [c.strip() for c in stripped.strip("|").split("|")]
            out.append('<table><thead><tr>')
            out.extend(f"<th>{inline(c)}</th>" for c in header_cells)
            out.append("</tr></thead><tbody>")
            i += 2
            while i < len(lines) and lines[i].strip().startswith("|"):
                row_cells = [c.strip() for c in lines[i].strip().strip("|").split("|")]
                out.append("<tr>" + "".join(f"<td>{inline(c)}</td>" for c in row_cells) + "</tr>")
                i += 1
            out.append("</tbody></table>")
            continue

        out.append(f"<p>{inline(stripped)}</p>")
        i += 1

    return "\n".join(out)


MATRIX_PAGE_TEMPLATE = """<!doctype html>
<html lang="id">
<head>
<meta charset="utf-8">
<title>Test Matrix — {slug}</title>
<style>
  body {{ font: 14px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         max-width: 1400px; margin: 2rem auto; padding: 0 1.5rem; color: #1f2328; }}
  h1, h2, h3 {{ border-bottom: 1px solid #d0d7de; padding-bottom: .3rem; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: 12.5px; }}
  th, td {{ border: 1px solid #d0d7de; padding: .4rem .5rem; text-align: left; vertical-align: top; }}
  th {{ background: #f6f8fa; position: sticky; top: 0; }}
  code {{ background: #f6f8fa; padding: .1rem .3rem; border-radius: 4px; }}
  .back-link {{ display: inline-block; margin-bottom: 1rem; font-size: 13px; }}
</style>
</head>
<body>
<a class="back-link" href="../playwright-report/index.html">&larr; Back to test report</a>
{body}
</body>
</html>
"""


def _render_all_matrices() -> list[tuple[str, Path]]:
    """Render every docs/qa/<slug>/test-matrix.md to a sibling .html.
    Returns [(slug, html_path_relative_to_QA_DIR), ...]."""
    rendered = []
    if not QA_DIR.is_dir():
        return rendered
    for md_path in sorted(QA_DIR.glob("*/test-matrix.md")):
        slug = md_path.parent.name
        body = _render_matrix_markdown(md_path.read_text(encoding="utf-8"))
        page = MATRIX_PAGE_TEMPLATE.format(slug=html_lib.escape(slug), body=body)
        html_path = md_path.with_suffix(".html")
        html_path.write_text(page, encoding="utf-8")
        rendered.append((slug, html_path.relative_to(QA_DIR)))
    return rendered


def _matrix_link_snippet(rendered: list[tuple[str, Path]]) -> str:
    if not rendered:
        return ""
    links = "\n".join(
        f'<a href="../{path.as_posix()}" target="_blank" rel="noopener">{html_lib.escape(slug)}</a>'
        for slug, path in rendered
    )
    return f"""{MATRIX_MARKER}
<style>
.wt-matrix-fab {{
  position: fixed; right: 1rem; bottom: 1rem; z-index: 9999;
  font: 13px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}}
.wt-matrix-fab summary {{
  list-style: none; cursor: pointer; background: #2563eb; color: #fff;
  border-radius: 999px; padding: .55rem 1rem; box-shadow: 0 2px 8px rgba(0,0,0,.25);
}}
.wt-matrix-fab summary::-webkit-details-marker {{ display: none; }}
.wt-matrix-fab[open] summary {{ border-radius: 12px 12px 0 0; }}
.wt-matrix-fab .wt-matrix-menu {{
  background: #fff; border: 1px solid #d0d7de; border-top: none; border-radius: 0 0 8px 8px;
  padding: .5rem; display: flex; flex-direction: column; gap: .3rem; min-width: 180px;
}}
.wt-matrix-menu a {{ color: #1f2328; text-decoration: none; padding: .2rem 0; }}
.wt-matrix-menu a:hover {{ text-decoration: underline; }}
</style>
<details class="wt-matrix-fab">
  <summary>Test Matrix</summary>
  <div class="wt-matrix-menu">
    {links}
  </div>
</details>
"""


def main() -> int:
    if not REPORT_PATH.is_file():
        print(f"error: {REPORT_PATH} not found — run the suite first (run_e2e.py)", file=sys.stderr)
        return 1

    html = REPORT_PATH.read_text(encoding="utf-8")
    if "</body>" not in html:
        print(f"error: {REPORT_PATH} has no </body> tag — unexpected report format", file=sys.stderr)
        return 1

    changed = False

    if MARKER not in html:
        html = html.replace("</body>", INJECTED_SCRIPT + "</body>")
        changed = True
        print("Added video speed controls")
    else:
        print("Video speed controls already present — skipping")

    rendered = _render_all_matrices()
    if rendered:
        for slug, _ in rendered:
            print(f"Rendered test matrix for '{slug}'")
        # Always refresh the injected menu (slugs/paths may have changed)
        # rather than skip on MATRIX_MARKER presence like the video
        # controls above — the .md sources can gain/lose slugs between runs.
        html = re.sub(rf"{re.escape(MATRIX_MARKER)}.*?</details>\n?", "", html, flags=re.DOTALL)
        html = html.replace("</body>", _matrix_link_snippet(rendered) + "</body>")
        changed = True
    else:
        print("No docs/qa/*/test-matrix.md found — skipping test matrix link")

    if changed:
        REPORT_PATH.write_text(html, encoding="utf-8")
        print(f"Updated {REPORT_PATH}")
    else:
        print(f"{REPORT_PATH} already up to date — nothing to do")
    return 0


if __name__ == "__main__":
    sys.exit(main())
